### PR TITLE
Lots of front-end work now

### PR DESCRIPTION
**Pull request by gorel**
- Account edit page
- Account HTML/CSS stuff
- Join a team after account creation

### CODE REVIEW

**Comment by oggnik** [comment]
A bug I found:
1. Create a new user
2. Click the school in the my account page
3. Click the team (May also want to update that so it doesn't show <Team Your_team_name>
4. Hit join team
5. Confirm and join

==> NameError: global name 'team_id' is not defined

Issue #18

**Comment by gorel** [comment]
What line is the NameError on?

**Comment by oggnik** [comment]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nickiogg/Documents/School/Fall_2015/ACM/acm-hscc/hscc/account/controllers.py", line 92, in join_team
    if form.validate_on_submit():
  File "/Library/Python/2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/nickiogg/Documents/School/Fall_2015/ACM/acm-hscc/hscc/account/forms.py", line 43, in validate
    team_id.errors.append("You're already a member of this team")
NameError: global name 'team_id' is not defined

**Comment by oggnik** [comment]
It also happens when you try to join a team from another school.

Edit: Line 51 of hscc/account/forms.py

**Comment by oggnik** [comment]
Looks good to me

**Pull request merged**
